export const queryKeys = {
  vehicle: {
    root: "vehicle",
    list: "vehicle/list",
    nextNodes: "vehicle/next-nodes",
    nodeUsers: "vehicle/node-users",
    detail: "vehicle/detail",
    tracking: "vehicle/tracking",
    menuBadge: "vehicle/menu-badge",
    detailSlot: "vehicle/detail-slot",
    suggestDriver: "vehicle/suggest-driver",
    listAll: "vehicle/list-all",
  },
  organizations: {
    getAll: "organizations/getAll",
    getRoot: "organizations/getRoot",
    getById: "organizations/getById",
    search: "organizations/search",
    all: "organizations/all",
    orgCVV: "organizations/org-cvv",
  },
  bpmn: {
    search: "bpmn2/search",
    detail: "bpmn2/getById",
    startNodes: "bpmn/start-nodes",
    nextNodes: "bpmn/next-nodes",
    nextConsultNodes: "bpmn/next-consult-nodes",
  },
  workflowConfig: {
    search: "workflow-config/search",
    detail: "workflow-config/getById",
  },
  users: {
    getAllUserByLead: "users/getAllUserByLead",
    assignTasks: "users/assign-tasks",
    getByAuthority: "users/getByAuthority",
    getByOrgs: "users/findListUserByOrgs",
    getByOutsideAgency: "outside-agency/search",
    getDocumentTemplate: "template/all",
    getDraftDocumentInTemplate: "template/draft/VAN_BAN_DI",
    allUserAndProcess: "users/all-user-and-process",
    listUserByOrg: "users/get-list-user",
    userLeadOrgBanTransfer: "users/user-lead-org-ban-transfer",
    search: "users/search",
    getByUserName: "users/getByUserName",
    secretarys: "users/secretarys",
    all: "users/all",
    getUsersInformationActive: "users/getUsersInformationActive",
    checkIam: "users/check-user-iam",
  },
  comments: {
    vehicleUsagePlan: "vehicle-usage-plan-comments",
  },
  personalstatus: {
    documents: "dashboard/documents",
    tasksFromLeadership: "dashboard/tasks-from-leadership",
    assignedTasks: "dashboard/assigned-tasks",
    schedule: "dashboard/schedule",
    stats: "dashboard/stats",
  },
  lead: {
    info: "lead-info",
  },
  documentOut: {
    root: "document-out",
    list: "document-out/list",
    detail: "document-out/detail",
    tracking: "document-out/tracking",
    init_draft_data: "document-out/init-draft",
    draft_list: "document-out/draft-list",
    draft_list_issued: "document-out/draft-list-issued",
    list_attachment: "document-out/list-attachment",
    basicSearchIncoming: "document-out/basic-search-incoming",
    advanceSearchIncoming: "document-out/advance-search-incoming",
    waitingSearch: "document-out/waiting-search",
    comments: "document-out/comments",
    findAllDocImportant: "document-out/findAllDoc-important",
    findBasicAllDoc: "document-out/findBasicAllDoc",
    docInManipulation: "document-out/docInManipulation",
  },
  calendar: {
    permissionBan: "calendar/permission-ban",
    byMonth: "calendar/by-month",
    byWeek: "calendar/by-week",
    business: "calendar/business",
    detail: "calendar/detail",
    history: "calendar/history",
    orgRoom: "calendar/org-room",
    roomList: "calendar/room-list",
    orgRoomList: "calendar/org-room-list",
  },
  document_in: {
    all_documents: "document_in/all_documents",
    list_root: "document_in/list",
    draft_handle: "document_in/draft-handle",
    draft_list: "document_in/draft-list",
    draft_list_issued: "document_in/draft-list-issued",
    check_action_retake: "document_in/check-action-retake",
    check_action_import_doc: "document_in/check-action-import-doc",
    reject: "document_in/reject",
    book_type: "document_in/book_type",
    list_attachment: "document_in/list-attachment",
    init_draft_data: "document_in/init_draft",
    quick_knowable_unread: "document_in/quick-knowable-unread",
    quick_knowable_read: "document_in/quick-knowable-read",
    important_documents: "document_in/important-documents",
    replyDoc: "document_in/reply-doc",
    orgIssued: "document_in/org-issued",
    taskAssignment: "document_in/task-assignment",
    detail: "document_in/detail",
    receivedDoc: "document_in/received-doc",
    comment: "document_in/comment",
    categoryWithCode: "document_in/category-with-code",
    taskReport: "document_in/task-report",
  },

  categories: {
    search: "categories/search",
    byType: "categories/byType",
  },
  categoryTypes: {
    list: "categoryTypes/list",
  },
  documentBook: {
    byType: "documentBook/byType",
    documents: "documentBook/documents",
    docFieldsCategory: "documentBook/docFieldsCategory",
    urgentCategory: "documentBook/urgentCategory",
    securityCategory: "documentBook/securityCategory",
  },
  documentBooks: {
    search: "documentBooks/search",
    detail: "documentBooks/detail",
    byType: "documentBooks/byType",
  },
  manageWatchList: {
    list: "watch-list",
    listOrgWaitFinish: "listOrgWaitFinish",
    orgParent: "orgParent",
    checkStatusWatchList: "checkStatusWatchList",
  },

  task: {
    findOrgAll: "task/findOrgAll",
    doSearchTaskFollow: "task/doSearchTaskFollow",
    getAction: "task/getAction",
    getUserFlow: "task/getUserFlow",
    getRealTime: "task/getRealTime",
    getListUserFollow: "task/getListUserFollow",
    getByUserExecute: "task/getByUserExecute",
    getTemplate: "task/getTemplate",
    getAll: "task/getAllTemplate",
    getDraftTemplate: "task/getDraftTemplate",
    getTracking: "task/getTracking",
    getFindByIdTask: "task/getFindByIdTask",
    getJobAssignerList: "task/getJobAssignerList",
    getCurrentJobAssigner: "task/getCurrentJobAssigner",
    commentList: "task/commentList",
    resultList: "task/resultList",
    assign: "task/assign",
    doSearchTask: "task/doSearchTask",
    getTaskOrgUserLead: "task/getTaskOrgUserLead",
    attachedDocument: "task/attachedDocument",
    getAllTaskStatistic: "task/getAllTaskStatistic",
    list: "task/list",
    combinationList: "task/combinationList",
    regularList: "task/regularList",
    getAllUsersByOrgAndSub: "task/getAllUsersByOrgAndSub",
    getTaskKpi: "task/getTaskKpi",
    getDetailKpi: "task/getDetailKpi",
    getDetailKpiTask: "task/getDetailKpiTask",
    dashboardByDepartment: "task/dashboardByDepartment",
    dashboardData: "task/dashboardData",
    dashboardListOrg: "task/dashboardListOrg",
    dashboardList: "task/dashboardList",
    listTasksByUser: "task/listTasksByUser",
    declaredTask: "task/declaredTask",
    listViewFollow: "task/listViewFollow",
  },
  document: {
    root: "document",
    checkTypeHandleByDoc: "document/checkTypeHandleByDoc",
    usersEvaluate: "document/usersEvaluate",
    listSend: "document/listSend",
  },
  field: {
    root: "field",
    fields: "field/fields",
  },
  value: {
    root: "value",
    values: "value/values",
  },
  usage: {
    root: "usage",
    values: "usage/values",
    list: "usage/list",
    categoryType: "usage/categoryType",
  },
  documentRecord: {
    fontList: "documentRecord/fontList",
    fontDetail: "documentRecord/fontDetail",
    root: "documentRecord",
    hstl: "documentRecord/hstl",
    listFolder: "documentRecord/listFolder",
    listByFolderIdNew: "documentRecord/listByFolderIdNew",
    listRootFolder: "documentRecord/listRootFolder",
    dataDetailByFolderId: "documentRecord/dataDetailByFolderId",
    folderDetailById: "documentRecord/folderDetailById",
    headingInit: "documentRecord/heading-init",
    headingTree: "documentRecord/heading-tree",
    hscv: "documentRecord/hscv",
    listVB: "documentRecord/listVB",
    allDocuments: "documentRecord/allDocuments",
    allOrgAndSub: "documentRecord/allOrgAndSub",
    loadHSCQ: "documentRecord/loadHSCQ",
    maintenancePeriods: "documentRecord/maintenance-periods",
    approvers: "documentRecord/approvers",
    listShare: "documentRecord/listShare",
  },
  tags: {
    root: "tags",
    unpage: "tags/unpage",
    search: "tags/search",
  },
  objects: {
    root: "objects",
  },
  outsideSystem: {
    root: "outside-system",
    lgspTracking: "outside-system/lgspTracking",
  },
  outSys: {
    getList: "out-sys/all",
    getHistoryList: "integrate/track/sys",
  },

  report: {
    unconfirmedReport: "report/unconfirmed-report",
    verifiedReport: "report/verified-report",
    titleList: "report/title-list",
    signerList: "report/signer-list",
    reportList: "report/report-list",
    organization: "report/organization",
  },
  docInternal: {
    root: "doc-internal",
    list: "doc-internal/list",
    search: "doc-internal/search",
    detail: "doc-internal/detail",
    comments: "doc-internal/comments",
    numberOrSign: "doc-internal/number-or-sign",
    attachments: "doc-internal/attachments",
    orgByParent: "doc-internal/org-by-parent",
    userApprove: "doc-internal/user-approve",
    userSign: "doc-internal/user-sign",
    usersLDCuc: "doc-internal/users-ld-cuc",
  },
  logBusiness: {
    root: "log-business",
    excel: "log-business/export",
    mapCategory: "map_category/getAll/",
  },
  retake: {
    document_in: "retake/document-in",
    document_out: "retake/document-out",
  },
  clericalOrg: {
    getList: "clerical/getClerical",
  },
  delegateFlow: {
    getList: "delegate_flow/list",
  },
  role: {
    getAll: "role/getAll",
    getUserActiveByRole: "role/getUserActiveByRole",
    getPositionActiveByRole: "role/getPositionActiveByRole",
  },
  module: {
    getAll: "module/getAll",
    getDetailModule: "module/getDetailModule",
  },
  profile: {
    detail: "profile/detail",
  },
  delegate: {
    getList: "delegate/getList",
    getListByHandleTypeAndStatus: "delegate/getListByHandleTypeAndStatus",
  },
  group: {
    search: "group/search",
  },
  taskv2: {
    findBasic: "taskv2/findBasic",
    getListListTaskAssigner: "taskv2/getListListTaskAssigner",
    getDetail: "taskv2/getDetail",
    departmentTaskList: "taskv2/departmentTaskList",
    countDepartmentTask: "taskv2/countDepartmentTask",
    detailDepartmentTask: "taskv2/detailDepartmentTask",
    getTaskOrgUserLeadV2: "taskv2/getTaskOrgUserLeadV2",
    assign: "taskv2/assign",
    attachedDocument: "taskv2/attachedDocument",
    list: "taskv2/list",
    combinationList: "taskv2/combinationList",
    getFindByIdTask: "taskv2/getFindByIdTask",
    getAction: "taskv2/getAction",
    commentList: "taskv2/commentList",
    resultList: "taskv2/resultList",
    getTracking: "taskv2/getTracking",
    getUserFlow: "taskv2/getUserFlow",
    getRealTime: "taskv2/getRealTime",
    getListUserFollow: "taskv2/getListUserFollow",
    getByUserExecute: "taskv2/getByUserExecute",
    getCurrentJobAssigner: "taskv2/getCurrentJobAssigner",
    doSearchTaskFollow: "taskv2/doSearchTaskFollow",
    dashboardData: "taskv2/dashboardData",
    dashboardByDepartment: "taskv2/dashboardByDepartment",
    getRegularWeek: "taskv2/getRegularWeek",
  },
  formConfig: {
    list: "form-config/list",
    simpleList: "form-config/simple-list",
    detail: "form-config/detail",
    apiEndpoints: "form-config/api-endpoints",
    typeList: "form-config/type-list",
  },
  formDynamic: {
    getDynamicForm: "form-dynamic/get-dynamic-form",
    getDynamicFormMain: "form-dynamic/get-dynamic-form-main",
  },
  valueDynamic: {
    search: "value-dynamic/search",
    detail: "value-dynamic/detail",
    tracking: "value-dynamic/tracking",
    calendar: "value-dynamic/calendar",
  },
  workFlow: {
    getFormNodeStart: "workflow/getFormNodeStart",
    getNextStartNode: "workflow/start-node",
    getNodeUser: "workflow/node/users",
    getStartNode: "workflow/start-node",
  },
  api: {
    list: "api/list",
    detail: "api/detail",
  },
  search: {
    quickSearch: "search/quick-search",
  },
  templateForm: {
    getTemplate: "template-form/get-template",
  },
} as const;
